storage:
  method: native

kick:
  message: '&cYou are banned. &r<reason>'
  expires:
    format: dd-MM-yyyy HH:mm
    message: ' &aExpires <expires>'

broadcast:
  message: <op> <type>ned <player>. <reason>
  expires:
    format: dd-MM-yyyy HH:mm
    message: ' Expires <expires>.'

info:
  timestamp:
    format: dd-MM-yyyy HH:mm
