name: ${project.name}
version: ${project.version}
description: Advanced ban management.

author: Jim Flaten
website: http://www.flaten.it/

main: ${main.class}
database: true

permissions:
  mjolnir.info:
    description: Gives access to Mjölnir information command and broadcasts.
    default: true

  mjolnir.ban.temp:
    description: Gives access to temporary Mjölnir banning.
    default: op

  mjolnir.ban.perm:
    description: Gives access to Mjölnir banning.
    default: op

  mjolnir.unban.temp:
    description: Gives access to temporary Mjölnir unbanning.

  mjolnir.unban.perm:
    description: Gives access to Mjölnir unbanning.
    default: op

commands:
  infractions:
    description: Gets information about a given player from Mjölnir.
    usage: /<command> [player]
    permission: <plugin name>.info

  tempban:
    description: Bans a given player in Mjölnir for the given amount of time, with an optional reason.
    usage: /<command> [player] [time] [reason]
    permission: <plugin name>.ban.temp

  ban:
    description: Bans a given player in Mjölnir, with an optional reason.
    usage: /<command> [player] [reason]
    permission: <plugin name>.ban.perm

  tempunban:
    description: Unbans a given player in Mjölnir for the given amount of time, with an optional reason.
    usage: /<command> [player] [time] [reason]
    permission: <plugin name>.unban.temp

  unban:
    description: Unbans a given player in Mjölnir, with an optional reason.
    usage: /<command> [player] [reason]
    permission: <plugin name>.unban.perm
